# rds.tf — Stage 2 step 1: RDS Postgres
#
# Security posture:
#  - Private subnets only, publicly_accessible = false — never reachable
#    from the internet, only from inside the VPC.
#  - Security group allows 5432 only from the EKS node security group
#    (nothing else, no VPC-wide CIDR rule).
#  - Storage + automated backups encrypted with our own KMS key.
#  - Master password is generated by Terraform (never typed, never in
#    tfvars/state as a readable default) and stored in Secrets Manager;
#    the app/Lambda reads it at runtime via IAM, not an env var baked into
#    a manifest.

resource "random_password" "db" {
  length  = 32
  special = false # keep it URL/connection-string safe; still 32 chars of entropy
}

resource "aws_secretsmanager_secret" "db" {
  name                    = "${var.name_prefix}/rds/master"
  description             = "Master credentials for the ${var.name_prefix} RDS instance"
  recovery_window_in_days = 0 # demo project — allow immediate deletion on `terraform destroy`
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id
  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db.result
    engine   = "postgres"
    host     = aws_db_instance.this.address
    port     = aws_db_instance.this.port
    dbname   = var.db_name
  })
}

resource "aws_db_subnet_group" "this" {
  name       = "${var.name_prefix}-db-subnets"
  subnet_ids = module.vpc.private_subnets
}

resource "aws_security_group" "rds" {
  name        = "${var.name_prefix}-rds-sg"
  description = "Allow Postgres only from the EKS worker nodes"
  vpc_id      = module.vpc.vpc_id

  egress {
    description = "No outbound requirement for a DB server; deny by default"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = []
  }
}

resource "aws_security_group_rule" "rds_from_eks_nodes" {
  type                     = "ingress"
  from_port                = 5432
  to_port                  = 5432
  protocol                 = "tcp"
  security_group_id        = aws_security_group.rds.id
  source_security_group_id = module.eks.node_security_group_id
  description              = "Postgres from EKS worker nodes"
}

resource "aws_db_instance" "this" {
  identifier     = "${var.name_prefix}-db"
  engine         = "postgres"
  engine_version = var.db_engine_version
  instance_class = var.db_instance_class

  db_name  = var.db_name
  username = var.db_username
  password = random_password.db.result

  allocated_storage     = var.db_allocated_storage
  max_allocated_storage = var.db_allocated_storage * 5 # storage autoscaling ceiling
  storage_type          = "gp3"
  storage_encrypted     = true
  kms_key_id            = aws_kms_key.rds.arn

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [aws_security_group.rds.id]
  publicly_accessible    = false

  multi_az                   = false # single-AZ keeps a demo cluster cheap; flip to true for a prod story
  backup_retention_period    = 7
  deletion_protection        = false # demo project — must be destroyable in one command
  skip_final_snapshot        = true
  copy_tags_to_snapshot      = true
  auto_minor_version_upgrade = true

  tags = {
    Project = var.name_prefix
  }
}
